# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.2

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/aejt/Documents/GitHub/fuego

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/aejt/Documents/GitHub/fuego

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all:
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/aejt/Documents/GitHub/fuego/CMakeFiles /Users/aejt/Documents/GitHub/fuego//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/aejt/Documents/GitHub/fuego/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

#=============================================================================
# Target rules for targets named version

# Build rule for target.
version:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 version
.PHONY : version

# fast build rule for target.
version/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/version.dir/build.make CMakeFiles/version.dir/build
.PHONY : version/fast

#=============================================================================
# Target rules for targets named upnpc-static

# Build rule for target.
upnpc-static:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 upnpc-static
.PHONY : upnpc-static

# fast build rule for target.
upnpc-static/fast:
	$(MAKE) $(MAKESILENT) -f external/miniupnpc/CMakeFiles/upnpc-static.dir/build.make external/miniupnpc/CMakeFiles/upnpc-static.dir/build
.PHONY : upnpc-static/fast

#=============================================================================
# Target rules for targets named BlockchainExplorer

# Build rule for target.
BlockchainExplorer:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 BlockchainExplorer
.PHONY : BlockchainExplorer

# fast build rule for target.
BlockchainExplorer/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/BlockchainExplorer.dir/build.make src/CMakeFiles/BlockchainExplorer.dir/build
.PHONY : BlockchainExplorer/fast

#=============================================================================
# Target rules for targets named Common

# Build rule for target.
Common:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Common
.PHONY : Common

# fast build rule for target.
Common/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/Common.dir/build.make src/CMakeFiles/Common.dir/build
.PHONY : Common/fast

#=============================================================================
# Target rules for targets named Crypto

# Build rule for target.
Crypto:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Crypto
.PHONY : Crypto

# fast build rule for target.
Crypto/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/Crypto.dir/build.make src/CMakeFiles/Crypto.dir/build
.PHONY : Crypto/fast

#=============================================================================
# Target rules for targets named CryptoNoteCore

# Build rule for target.
CryptoNoteCore:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 CryptoNoteCore
.PHONY : CryptoNoteCore

# fast build rule for target.
CryptoNoteCore/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/CryptoNoteCore.dir/build.make src/CMakeFiles/CryptoNoteCore.dir/build
.PHONY : CryptoNoteCore/fast

#=============================================================================
# Target rules for targets named Http

# Build rule for target.
Http:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Http
.PHONY : Http

# fast build rule for target.
Http/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/Http.dir/build.make src/CMakeFiles/Http.dir/build
.PHONY : Http/fast

#=============================================================================
# Target rules for targets named InProcessNode

# Build rule for target.
InProcessNode:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 InProcessNode
.PHONY : InProcessNode

# fast build rule for target.
InProcessNode/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/InProcessNode.dir/build.make src/CMakeFiles/InProcessNode.dir/build
.PHONY : InProcessNode/fast

#=============================================================================
# Target rules for targets named Logging

# Build rule for target.
Logging:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Logging
.PHONY : Logging

# fast build rule for target.
Logging/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/Logging.dir/build.make src/CMakeFiles/Logging.dir/build
.PHONY : Logging/fast

#=============================================================================
# Target rules for targets named NodeRpcProxy

# Build rule for target.
NodeRpcProxy:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NodeRpcProxy
.PHONY : NodeRpcProxy

# fast build rule for target.
NodeRpcProxy/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/NodeRpcProxy.dir/build.make src/CMakeFiles/NodeRpcProxy.dir/build
.PHONY : NodeRpcProxy/fast

#=============================================================================
# Target rules for targets named Rpc

# Build rule for target.
Rpc:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Rpc
.PHONY : Rpc

# fast build rule for target.
Rpc/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/Rpc.dir/build.make src/CMakeFiles/Rpc.dir/build
.PHONY : Rpc/fast

#=============================================================================
# Target rules for targets named P2P

# Build rule for target.
P2P:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 P2P
.PHONY : P2P

# fast build rule for target.
P2P/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/P2P.dir/build.make src/CMakeFiles/P2P.dir/build
.PHONY : P2P/fast

#=============================================================================
# Target rules for targets named Serialization

# Build rule for target.
Serialization:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Serialization
.PHONY : Serialization

# fast build rule for target.
Serialization/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/Serialization.dir/build.make src/CMakeFiles/Serialization.dir/build
.PHONY : Serialization/fast

#=============================================================================
# Target rules for targets named System

# Build rule for target.
System:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 System
.PHONY : System

# fast build rule for target.
System/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/System.dir/build.make src/CMakeFiles/System.dir/build
.PHONY : System/fast

#=============================================================================
# Target rules for targets named Transfers

# Build rule for target.
Transfers:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Transfers
.PHONY : Transfers

# fast build rule for target.
Transfers/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/Transfers.dir/build.make src/CMakeFiles/Transfers.dir/build
.PHONY : Transfers/fast

#=============================================================================
# Target rules for targets named Wallet

# Build rule for target.
Wallet:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Wallet
.PHONY : Wallet

# fast build rule for target.
Wallet/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/Wallet.dir/build.make src/CMakeFiles/Wallet.dir/build
.PHONY : Wallet/fast

#=============================================================================
# Target rules for targets named PaymentGate

# Build rule for target.
PaymentGate:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 PaymentGate
.PHONY : PaymentGate

# fast build rule for target.
PaymentGate/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/PaymentGate.dir/build.make src/CMakeFiles/PaymentGate.dir/build
.PHONY : PaymentGate/fast

#=============================================================================
# Target rules for targets named JsonRpcServer

# Build rule for target.
JsonRpcServer:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 JsonRpcServer
.PHONY : JsonRpcServer

# fast build rule for target.
JsonRpcServer/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/JsonRpcServer.dir/build.make src/CMakeFiles/JsonRpcServer.dir/build
.PHONY : JsonRpcServer/fast

#=============================================================================
# Target rules for targets named SimpleWalletLib

# Build rule for target.
SimpleWalletLib:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SimpleWalletLib
.PHONY : SimpleWalletLib

# fast build rule for target.
SimpleWalletLib/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/SimpleWalletLib.dir/build.make src/CMakeFiles/SimpleWalletLib.dir/build
.PHONY : SimpleWalletLib/fast

#=============================================================================
# Target rules for targets named Daemon

# Build rule for target.
Daemon:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Daemon
.PHONY : Daemon

# fast build rule for target.
Daemon/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/Daemon.dir/build.make src/CMakeFiles/Daemon.dir/build
.PHONY : Daemon/fast

#=============================================================================
# Target rules for targets named TestnetDaemon

# Build rule for target.
TestnetDaemon:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 TestnetDaemon
.PHONY : TestnetDaemon

# fast build rule for target.
TestnetDaemon/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/TestnetDaemon.dir/build.make src/CMakeFiles/TestnetDaemon.dir/build
.PHONY : TestnetDaemon/fast

#=============================================================================
# Target rules for targets named SimpleWallet

# Build rule for target.
SimpleWallet:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SimpleWallet
.PHONY : SimpleWallet

# fast build rule for target.
SimpleWallet/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/SimpleWallet.dir/build.make src/CMakeFiles/SimpleWallet.dir/build
.PHONY : SimpleWallet/fast

#=============================================================================
# Target rules for targets named PaymentGateService

# Build rule for target.
PaymentGateService:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 PaymentGateService
.PHONY : PaymentGateService

# fast build rule for target.
PaymentGateService/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/PaymentGateService.dir/build.make src/CMakeFiles/PaymentGateService.dir/build
.PHONY : PaymentGateService/fast

#=============================================================================
# Target rules for targets named Optimizer

# Build rule for target.
Optimizer:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Optimizer
.PHONY : Optimizer

# fast build rule for target.
Optimizer/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/Optimizer.dir/build.make src/CMakeFiles/Optimizer.dir/build
.PHONY : Optimizer/fast

#=============================================================================
# Target rules for targets named testnet-wallet-cli

# Build rule for target.
testnet-wallet-cli:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 testnet-wallet-cli
.PHONY : testnet-wallet-cli

# fast build rule for target.
testnet-wallet-cli/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/testnet-wallet-cli.dir/build.make src/CMakeFiles/testnet-wallet-cli.dir/build
.PHONY : testnet-wallet-cli/fast

#=============================================================================
# Target rules for targets named Fuegotor

# Build rule for target.
Fuegotor:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Fuegotor
.PHONY : Fuegotor

# fast build rule for target.
Fuegotor/fast:
	$(MAKE) $(MAKESILENT) -f src/FuegoTor/CMakeFiles/Fuegotor.dir/build.make src/FuegoTor/CMakeFiles/Fuegotor.dir/build
.PHONY : Fuegotor/fast

#=============================================================================
# Target rules for targets named EldernodeIndexManager

# Build rule for target.
EldernodeIndexManager:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 EldernodeIndexManager
.PHONY : EldernodeIndexManager

# fast build rule for target.
EldernodeIndexManager/fast:
	$(MAKE) $(MAKESILENT) -f src/EldernodeIndexManager/CMakeFiles/EldernodeIndexManager.dir/build.make src/EldernodeIndexManager/CMakeFiles/EldernodeIndexManager.dir/build
.PHONY : EldernodeIndexManager/fast

#=============================================================================
# Target rules for targets named BurnDepositValidationService

# Build rule for target.
BurnDepositValidationService:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 BurnDepositValidationService
.PHONY : BurnDepositValidationService

# fast build rule for target.
BurnDepositValidationService/fast:
	$(MAKE) $(MAKESILENT) -f src/BurnDepositValidationService/CMakeFiles/BurnDepositValidationService.dir/build.make src/BurnDepositValidationService/CMakeFiles/BurnDepositValidationService.dir/build
.PHONY : BurnDepositValidationService/fast

#=============================================================================
# Target rules for targets named fuego-tui

# Build rule for target.
fuego-tui:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 fuego-tui
.PHONY : fuego-tui

# fast build rule for target.
fuego-tui/fast:
	$(MAKE) $(MAKESILENT) -f tui/CMakeFiles/fuego-tui.dir/build.make tui/CMakeFiles/fuego-tui.dir/build
.PHONY : fuego-tui/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... fuego-tui"
	@echo "... version"
	@echo "... BlockchainExplorer"
	@echo "... BurnDepositValidationService"
	@echo "... Common"
	@echo "... Crypto"
	@echo "... CryptoNoteCore"
	@echo "... Daemon"
	@echo "... EldernodeIndexManager"
	@echo "... Fuegotor"
	@echo "... Http"
	@echo "... InProcessNode"
	@echo "... JsonRpcServer"
	@echo "... Logging"
	@echo "... NodeRpcProxy"
	@echo "... Optimizer"
	@echo "... P2P"
	@echo "... PaymentGate"
	@echo "... PaymentGateService"
	@echo "... Rpc"
	@echo "... Serialization"
	@echo "... SimpleWallet"
	@echo "... SimpleWalletLib"
	@echo "... System"
	@echo "... TestnetDaemon"
	@echo "... Transfers"
	@echo "... Wallet"
	@echo "... testnet-wallet-cli"
	@echo "... upnpc-static"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

