#define BUILD_COMMIT_ID "@VERSION@"
#define PROJECT_RELEASE "Wildfire"
#define PROJECT_VERSION "1.10.02"
#define PROJECT_RELEASE_VERSION "v" PROJECT_VERSION "-" PROJECT_RELEASE
#define PROJECT_VERSION_BUILD_NO "1152"
#define PROJECT_VERSION_LONG PROJECT_RELEASE  " || " "v" PROJECT_VERSION "." PROJECT_VERSION_BUILD_NO "(" BUILD_COMMIT_ID ")"
#define FIRE_WALLET_RELEASE_VERSION "Fire Wallet " PROJECT_RELEASE_VERSION

#define TESTNET_DAEMON_VERSION "10.01.014"
// 10.00 <-BLOCK MAJOR Version being tested / .001 number of genesis resets++

#define UPCOMING_MAINNET_RELEASE "PROPHETS"
#define UPCOMING_MAINNET_VERSION PROJECT_VERSION "." PROJECT_VERSION_BUILD_NO "(" BUILD_COMMIT_ID ")" UPCOMING_MAINNET_RELEASE
