name: Ubuntu 24.04 Release

on:
  push:
    tags:
      - "*"

jobs:
  build-ubuntu24:
    name: Ubuntu 24.04
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake libboost-all-dev libssl-dev libicu-dev libjsoncpp-dev

      - name: Build
        id: build
        run: |
          xfg_version=$(echo "$GITHUB_REF" | sed 's|refs/tags/||')
          release_name=fuego-cli-ubuntu-2404-v"$xfg_version"

          cmake -B build -DCMAKE_BUILD_TYPE=Release
          make -C build -j$(nproc)

          mkdir -p "$release_name"
          for f in build/src/*; do [[ -x $f && -f $f ]] && strip "$f" && cp "$f" "$release_name/"; done
          tar -czf "$release_name".tar.gz "$release_name"
          sha256=$(sha256sum "$release_name".tar.gz | awk '{print toupper($1)}')
          asset_path="./$release_name.tar.gz"
          echo "sha256=${sha256}" >> $GITHUB_OUTPUT
          echo "release_name=${release_name}.tar.gz" >> $GITHUB_OUTPUT
          echo "asset_path=${asset_path}" >> $GITHUB_OUTPUT
          echo "xfg_version=${xfg_version}" >> $GITHUB_OUTPUT

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ steps.build.outputs.asset_path }}
          name: Fuego CLI Suite v${{ steps.build.outputs.xfg_version }}
          body: |
            [Download for Ubuntu 24.04](../../releases/download/${{ steps.build.outputs.xfg_version }}/${{ steps.build.outputs.release_name }}) **${{ steps.build.outputs.release_name }}**

            `SHA256 : ${{ steps.build.outputs.sha256 }}`
          append_body: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
