name: Windows Release

on:
  push:
    tags:
      - "*"

jobs:
  build-windows:
    name: Windows
    runs-on: windows-2025
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1

      - name: Install OpenSSL
        shell: powershell
        run: |
          choco install openssl -y
          echo "OPENSSL_ROOT_DIR=C:\Program Files\OpenSSL-Win64" >> $env:GITHUB_ENV

      - name: Download and Install Boost 1.85
        shell: powershell
        run: |
          choco install boost-msvc-14.3 --version=1.85.0 -y --allow-downgrade
          echo "BOOST_ROOT=C:\tools\boost\boost_1_85_0" >> $env:GITHUB_ENV
          echo "BOOST_INCLUDE_DIRS=C:\tools\boost\boost_1_85_0\include" >> $env:GITHUB_ENV

      - name: Build
        id: build
        shell: powershell
        run: |
          $sha = "${{ github.sha }}"
          $xfg_ver = $sha.SubString(0,7)
          $release_name = "fuego-cli-win64-v$xfg_ver"

          mkdir build
          cd build
          cmake -G "Visual Studio 17 2022" -A x64 `
            -DBOOST_ROOT="$env:BOOST_ROOT" `
            -DBOOST_INCLUDE_DIRS="$env:BOOST_INCLUDE_DIRS" `
            -DOPENSSL_ROOT_DIR="$env:OPENSSL_ROOT_DIR" ..
          msbuild fuegoX.sln /p:Configuration=Release /m

          cd src\Release
          Compress-Archive -Path *.exe -DestinationPath "$release_name.zip"
          $sha256 = (Get-FileHash "$release_name.zip").Hash
          $asset_path = ".\src\Release\$release_name.zip"
          echo "sha256=${sha256}" >> $env:GITHUB_OUTPUT
          echo "release_name=${release_name}.zip" >> $env:GITHUB_OUTPUT
          echo "asset_path=${asset_path}" >> $env:GITHUB_OUTPUT
          echo "xfg_version=${xfg_ver}" >> $env:GITHUB_OUTPUT

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ steps.build.outputs.asset_path }}
          name: Fuego CLI Suite v${{ steps.build.outputs.xfg_version }}
          body: |
            [Download for Windows](../../releases/download/${{ steps.build.outputs.xfg_version }}/${{ steps.build.outputs.release_name }}) **${{ steps.build.outputs.release_name }}**

            `SHA256 : ${{ steps.build.outputs.sha256 }}`
          append_body: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
